import { brand, Brand } from '@gglib/utils'

export type RenderSortPriority = Brand<string, 'RenderSortPriority'>
export const RenderSortPriority = {
  State: brand<RenderSortPriority>('state'),
  Depth: brand<RenderSortPriority>('depth'),
}

export type RenderItemFlags = Brand<number, 'RenderItemFlags'>
export const RenderItemFlags = {
  Opaque: brand<RenderItemFlags>(1 << 0),
  Transparent: brand<RenderItemFlags>(1 << 1),
  ShadowCaster: brand<RenderItemFlags>(1 << 2),
  Overlay: brand<RenderItemFlags>(1 << 3),
}

export type RenderFilter = {
  includeMask: RenderItemFlags
  excludeMask: RenderItemFlags
}

export const RenderFilter = {
  Opaque: {
    includeMask: RenderItemFlags.Opaque,
    excludeMask: brand<RenderItemFlags>(0),
  } satisfies RenderFilter,
  Transparent: {
    includeMask: RenderItemFlags.Transparent,
    excludeMask: brand<RenderItemFlags>(0),
  } satisfies RenderFilter,
  ShadowCaster: {
    includeMask: RenderItemFlags.ShadowCaster,
    excludeMask: brand<RenderItemFlags>(0),
  } satisfies RenderFilter,
  Overlay: {
    includeMask: RenderItemFlags.Overlay,
    excludeMask: brand<RenderItemFlags>(0),
  } satisfies RenderFilter,
}

/**
 * An object holding common components that are used to create a sort key for a render item.
 * Each component contributes to a part of the sort key. The actual key is generated by the {@link RenderListMode.getKey} function,
 * which packs these components into a single bigint.
 */
export interface Sortable {
  /**
   * The layer component. Can be a layer ID or a combination of application-specific flags.
   */
  layer: number
  /**
   * The render state ID that corresponds to a pipeline state e.g. blend state.
   */
  state: number
  /**
   * The depth component, usually the distance from the camera to the item in view space.
   */
  depth: number
  /**
   * The material ID
   */
  material: number
  /**
   * The material ID
   */
  geometry: number
}

/**
 * Defines the sorting andfilter behavior for render items in a render pass.
 */
export class RenderListMode {
  public static Opaque = new RenderListMode(RenderSortPriority.Depth, RenderItemFlags.Opaque)
  public static Transparent = new RenderListMode(RenderSortPriority.Depth, RenderItemFlags.Transparent)
  public static Shadow = new RenderListMode(RenderSortPriority.State, RenderItemFlags.ShadowCaster)

  public readonly mask: RenderItemFlags
  public readonly priority: RenderSortPriority

  public constructor(priority: RenderSortPriority, mask: RenderItemFlags) {
    this.mask = mask
    this.priority = priority
    this.getKey = this.buildKeyFn(mask, priority)
  }

  /**
   * Generates a sort key for a given render item based on the components defined in the item and the sorting behavior of this mode.
   * @param item
   * @returns
   */
  public getKey(item: Sortable): bigint {
    return BigInt(0)
  }

  protected buildKeyFn(mask: RenderItemFlags, priority: RenderSortPriority): (item: Sortable) => bigint {
    if (mask & RenderItemFlags.Transparent) {
      return priority === RenderSortPriority.Depth ? sortTransparentBackToFront : sortStateFirst
    }
    return priority === RenderSortPriority.Depth ? sortOpaqueFrontToBack : sortStateFirst
  }
}

// ---------- Sort key implementations ----------
// Packed into bigint: [layer | pipeline | material | geometry | depth]

function sortStateFirst(item: Sortable): bigint {
  // pipeline/material grouping, depth optional
  const depthBits = (item.depth * 255) | 0 // low-resolution depth
  return (
    (BigInt(item.layer) << BigInt(56)) |
    (BigInt(item.state) << BigInt(40)) |
    (BigInt(item.material) << BigInt(24)) |
    (BigInt(item.geometry) << BigInt(8)) |
    BigInt(depthBits)
  )
}

function sortOpaqueFrontToBack(item: Sortable): bigint {
  // 64-bit layout:
  // [ 56–63 ] layer    (8)
  // [ 30–55 ] depth    (26)
  // [ 20–29 ] state    (10)
  // [ 10–19 ] material (10)
  // [  0–9  ] geometry (10)

  const depthBits = Math.min((item.depth * 67108863) | 0, 67108863) // 26-bit

  return (
    BigInt(item.geometry) |
    (BigInt(item.material) << BigInt(10)) |
    (BigInt(item.state) << BigInt(20)) |
    (BigInt(depthBits) << BigInt(30)) |
    (BigInt(item.layer) << BigInt(56))
  )
}

function sortTransparentBackToFront(item: Sortable): bigint {
  const depthBits = 67108863 - ((item.depth * 67108863) | 0) // reverse depth
  return (
    (BigInt(item.layer) << BigInt(56)) |
    (BigInt(depthBits) << BigInt(30)) |
    (BigInt(item.state) << BigInt(20)) |
    (BigInt(item.material) << BigInt(10)) |
    BigInt(item.geometry)
  )
}
